### ISSUE TITLE
Conflict with Mover/Mover Tuning

### ISSUE THREAD

**Issue by collonix676** [bexem/PlexCache#19]
I'm having an issue where PlexCache is moving files to the cache (works well and is great) and then when mover runs it moves them back to the array. The next time PlexCache runs it moves files back to the cache... and on and on. I understand the two parts are operating as they should but I'd like to avoid files being shuffled back and forth unnecessarily.

Is there some setting that I'm missing in either setting up PlexCache or in Mover Tuning?

I know that it is possible to have Mover Tuning ignore files listed inside of text file; is it possible to have the PlexCache script generate a text file of the files it wants to keep on the cache?

**Comment by bexem** [comment]
Hi there! 

I personally have the mover tuning set up to run only when my cache drive reach a specific threshold, so it doesn’t really conflict with the script.

But it would be possible to implement the generation of a text file containing all the files that needs to stay in the cache…I’m currently fixing another issue but I will definitely look into this 😊

**Comment by collonix676** [comment]
Normally it isn't an issue because my cache usage isn't near the threshold like you have setup. But when things get near capacity it ends up with things moving back and forth.

> I will definitely look into this 😊

That would be great!

**Comment by collonix676** [comment]
Awesome - thanks!

The list is produced as expected but a little testing and it seems like the paths in  the plexcache_cache_files_exclude.txt should be in

`/mnt/cache/media/tv/... `format, rather than

`/mnt/user/media/tv/...`

**Comment by bexem** [comment]
You are absolutely correct, have a look at the just updated one, I also made sure it updates the file each time.
Let me know! ☺️

**Comment by collonix676** [comment]
I'm still getting `/mnt/user/media/tv/...` as the output.

**Comment by bexem** [comment]
Are you checking the right file? I did change the name of the file to plexcache_mover_files_to_exclude.txt so I just want to be sure.

**Comment by collonix676** [comment]
Ah, I hadn't noticed the name change - but the new file is still showing the `/mnt/user/media/tv/..` format.

**Comment by bexem** [comment]
You are absolutely correct, I referenced the wrong variable in the github version. Now it will only output cache files.

**Comment by collonix676** [comment]
Perfect - it is now running as expected.

Thanks so much for doing this!
