### ISSUE TITLE
Ownership/Permissions issue

### ISSUE THREAD

**Issue by collonix676** [bexem/PlexCache#29]
Running on Unraid through UserScripts is creating permissions issues.

Files are ending up with root/root ownership rather than nobody/users. Running the new permissions tool fixes it.

Is there some way to adjust UserScripts settings or the script to ensure the correct ownership/permissions?

**Comment by bexem** [comment]
The script should already address that:

```
def move_file(move_cmd):
    src, dest = move_cmd
    try:
        if os_linux:
            stat_info = os.stat(src)
            uid = stat_info.st_uid
            gid = stat_info.st_gid
            # Move the file first
            shutil.move(src, dest)
            # Then set the owner and group to the original values <----------
            os.chown(dest, uid, gid)
            original_umask = os.umask(0)
            os.chmod(dest, permissions)
            os.umask(original_umask)
        else:  # Windows logic
            shutil.move(src, dest)
            # For more granular Windows permissions, you'd use the win32security module here.
        logging.info(f"Moved file from {src} to {dest} with original permissions and owner.")
        return 0
    except (FileNotFoundError, PermissionError, Exception) as e:
        logging.error(f"Error moving file: {str(e)}")
        return 1
```

But considering is apparently not working for you a workaround could be running the script like this instead:
`sudo -u nobody python /path/to/plexcache.py`

**Comment by collonix676** [comment]
The v1.3.1 release doesn't seem to include this code but I've copied across the most recent raw code and it looks to be working correctly now.

Thank you!
